version: '3.9'
services:

  #MYSQL
  mysql:
    build: "./docker/mysql"
    container_name: "${APPNAME}-mysql"
    restart: "always"
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TIMEZONE}
    security_opt:
      - seccomp:unconfined
    volumes:
      #configuração do armazenamento do banco de dados
      - "./docker/mysql/data:/var/lib/mysql"